enum actions {
	UPLOAD_FILE = "UPLOAD_FILE",
	NAME = "NAME",
	NEXT_STEP = "NEXT_STEP",
	PREVIOUS_STEP = "PREVIOUS_STEP",
	ADDITIONAL_INFO = "ADDITIONAL_INFO",
	ADDITIONAL_INFO_LINK = "ADDITIONAL_INFO_LINK",
	DISPLAY_TYPE = "DISPLAY_TYPE",
	UPLOAD_DISPLAY_FILE = "UPLOAD_DISPLAY_FILE",
	PLAN = "PLAN",
	EXPIRATION_DATE = "EXPIRATION_DATE",
	CARD_NUMBER = "CARD_NUMBER",
	CVV = "CVV",
	CHECKBOX = "CHECKBOX",
	CHANGE_CATEGORY = "CHANGE_CATEGORY",
	LOCATION_SEARCHED = "LOCATION_SEARCHED",
	LOCATION_FETCHED = "LOCATION_FETCHED",
	LOCATION_SELECTED = "LOCATION_SELECTED",
	GET_POSITION = "GET_POSITION",
	TRIGGER_LEFT_TRANSITION = "TRIGGER_LEFT_TRANSITION",
	TRIGGER_RIGHT_TRANSITION = "TRIGGER_RIGHT_TRANSITION",
}

export default actions;
