enum errorTypes {
	INVALID_EMAIL = "INVALID_EMAIL",
	EMAIL_TAKEN = "EMAIL_TAKEN",
	INVALID_PASSWORD = "INVALID_PASSWORD",
	PASSWORD_NOT_MATCH = "PASSWORD_NOT_MATCH",
	REQUIRED = "REQUIRED",
	INVALID_USERNAME = "INVALID_USERNAME",
}

export default errorTypes;
